In [51]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import cv2 as cv

%matplotlib inline

In [52]:
df = pd.read_csv('frames_label.csv')
df = df.fillna(0)
df

                                            file  label
0       ./frames/S001_v001/S001_v001_frame_1.jpg    0.0
1       ./frames/S001_v001/S001_v001_frame_2.jpg    0.0
2       ./frames/S001_v001/S001_v001_frame_3.jpg    0.0
3       ./frames/S001_v001/S001_v001_frame_4.jpg    0.0
4       ./frames/S001_v001/S001_v001_frame_5.jpg    0.0
...                                          ...    ...
15899  ./frames/S020_v012/S020_v012_frame_52.jpg    0.0
15900  ./frames/S020_v012/S020_v012_frame_53.jpg    0.0
15901  ./frames/S020_v012/S020_v012_frame_54.jpg    0.0
15902  ./frames/S020_v012/S020_v012_frame_55.jpg    0.0
15903  ./frames/S020_v012/S020_v012_frame_56.jpg    0.0

[15904 rows x 2 columns]

In [53]:
video_source = []
frame_count = []
for file in df['file']:
    video_source.append(file.split('/')[2])
    frame_count.append(file.split('/')[-1][10:-4])

df['video_source'] = video_source
df['frame_count'] = frame_count

df

,file,label,video_source,frame_count
0,./frames/S001_v001/S001_v001_frame_1.jpg,0.0,S001_v001,frame_1
1,./frames/S001_v001/S001_v001_frame_2.jpg,0.0,S001_v001,frame_2
2,./frames/S001_v001/S001_v001_frame_3.jpg,0.0,S001_v001,frame_3
3,./frames/S001_v001/S001_v001_frame_4.jpg,0.0,S001_v001,frame_4
4,./frames/S001_v001/S001_v001_frame_5.jpg,0.0,S001_v001,frame_5
...,...,...,...,...
15899,./frames/S020_v012/S020_v012_frame_52.jpg,0.0,S020_v012,frame_52
15900,./frames/S020_v012/S020_v012_frame_53.jpg,0.0,S020_v012,frame_53
15901,./frames/S020_v012/S020_v012_frame_54.jpg,0.0,S020_v012,frame_54
15902,./frames/S020_v012/S020_v012_frame_55.jpg,0.0,S020_v012,frame_55
15903,./frames/S020_v012/S020_v012_frame_56.jpg,0.0,S020_v012,frame_56

In [54]:
cough = df[df['label'] == 1]
not_cough = df[df['label'] == 0]

In [55]:
os.mkdir('videos_labelled')
os.mkdir('./videos_labelled/cough')
os.mkdir('./videos_labelled/not_cough')
for vid_source in df['video_source'].unique():
    os.mkdir('./videos_labelled/cough/' + vid_source)
    os.mkdir('./videos_labelled/not_cough/' + vid_source)

In [56]:
for index, row in cough.iterrows():
    im = cv.imread(row['file'])
    fname = './videos_labelled/cough/' + row['video_source'] + '/' + row['video_source'] + '_' + row['frame_count'] + '.jpg'
    cv.imwrite(fname, im)
    
for index, row in not_cough.iterrows():
    im = cv.imread(row['file'])
    fname = './videos_labelled/not_cough/' + row['video_source'] + '/' + row['video_source'] + '_' + row['frame_count'] + '.jpg'
    cv.imwrite(fname, im)